// <auto-generated />
using HippoRecipeApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HippoRecipeApi.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250409125521_SeedDataUpdate")]
    partial class SeedDataUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HippoRecipeApi.Models.Recipe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ingredients")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Recipes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Creamy Garlic Pasta perfect for meal prep",
                            Ingredients = "5 Fedd hvitløk\n    4Tomater\n    2Paprika\n    2tsLøkpulver\n    1ts Oregano\n    1ts Basilikum\n    4ts Paprika krydder\n    180ml Kyllingbuljong\n    240grams Kesam\n    800grams Kjøttdeig\n    500grams Pasta\n    50grams Parmesan\n",
                            Instructions = "Kutt tomater og paprika i biter. Rasp hvitløk.\n    Ha olje i ei panne og stek tomater og paprika. Tilsett litt salt og pepper. La dette steke i 6 minutter.\n    Kok opp vann til pasta. Tilsett hvitløk til tomatene og paprikaen å la det steke i 4 minutter.\n    Tilsett halvparten av kryddere og stek i 3 minutter\n    Tilsett kyllingbuljong og kok i 10 minutter\n    La sausen kjøle seg ned før den blendes sammen med kesam og blend til den er kremet\n    Kok pasta 1 minutt mindre enn pakken krever\n    Stek kjøttdeig til den er nesten helt gjennomstekt. Tilsett resten av kryddere\n    Tilsett sausen fra blenderen til kjøttdeigen og la det steke i 2 minutter\n    Når pastaen er ferdig hell den over til kjøttdeigen og sausen. Bland og la den koke i 1-2 minutter\n",
                            Name = "Creamy Garlic Pasta"
                        });
                });

            modelBuilder.Entity("HippoRecipeApi.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TagName = "Pasta"
                        },
                        new
                        {
                            Id = 2,
                            TagName = "Lunsj"
                        },
                        new
                        {
                            Id = 3,
                            TagName = "Middag"
                        });
                });

            modelBuilder.Entity("RecipeTag", b =>
                {
                    b.Property<int>("RecipesId")
                        .HasColumnType("integer");

                    b.Property<int>("TagsId")
                        .HasColumnType("integer");

                    b.HasKey("RecipesId", "TagsId");

                    b.HasIndex("TagsId");

                    b.ToTable("RecipeTag");

                    b.HasData(
                        new
                        {
                            RecipesId = 1,
                            TagsId = 1
                        },
                        new
                        {
                            RecipesId = 1,
                            TagsId = 2
                        },
                        new
                        {
                            RecipesId = 1,
                            TagsId = 3
                        });
                });

            modelBuilder.Entity("RecipeTag", b =>
                {
                    b.HasOne("HippoRecipeApi.Models.Recipe", null)
                        .WithMany()
                        .HasForeignKey("RecipesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HippoRecipeApi.Models.Tag", null)
                        .WithMany()
                        .HasForeignKey("TagsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
